CREATE DATABASE scuola_db;

USE scuola_db;

CREATE TABLE utenti (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  cognome VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  ruolo ENUM('studente', 'professore') NOT NULL,
  creato_il TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
